# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuesConfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='last_name',
        ),
        migrations.AddField(
            model_name='test',
            name='Answer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='test',
            name='Keyword',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='test',
            name='Message',
            field=models.CharField(default='', max_length=30),
        ),
    ]
